---
kind: pipeline
type: docker
name: default

steps:
- name: Setup the remotes
  image: alpine/git
  commands:
    - git remote set-url origin hg::https://hg.mozilla.org/mozilla-unified
    - git remote update
    - git remote add dot https://github.com/dothq/browser-ff
  
- name: Bootstrap
  image: bash
  commands:
    - ./mach bootstrap --no-interactive

- name: Build Dot Browser
  image: bash
  commands:
    - ./mach build