name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install git-cinnabar
        run: |
          sudo git clone https://github.com/glandium/git-cinnabar /usr/bin/git-cinnabar
          export PATH="/usr/bin/git-cinnabar:$PATH"
          git cinnabar download
      - name: Clone repository
        run: git clone https://github.com/dothq/browser-ff .
      - name: Setup remotes
        run: |
          git remote set-url origin hg::https://hg.mozilla.org/mozilla-unified
          git remote update
          git remote add dot https://github.com/dothq/browser-ff
      - name: Bootstrap
        run: ./mach bootstrap --no-interactive
      - name: Build
        run: ./mach build
